# lightning.pytorch==2.1.0
seed_everything: true
model:
  class_path: ResNet18
  init_args:
    num_channels: 12
    num_classes: 1
data:
  class_path: S2Classification
  init_args:
    root_dir: "path/to/dataset"
    batch_size: 32
trainer:
  callbacks:
    - class_path: ModelCheckpoint
      init_args:
        filename: "{epoch}-{step}"
        save_last: true
    - class_path: ModelCheckpoint
      init_args:
        monitor: "validation/f1"
        mode: max
        filename: "epoch={epoch}-step={step}-f1={validation/f1:.4f}"
        auto_insert_metric_name: false
        save_weights_only: true
    - LearningRateMonitor
optimizer:
  class_path: torch.optim.SGD
  init_args:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
    nesterov: true
lr_scheduler:
  class_path: torch.optim.lr_scheduler.StepLR
  init_args:
    step_size: 50
    gamma: 0.1
